import re

START_KW = "\x02"
END_KW = "\x03"


def inject_keywords(input: str):
    return PATTERN.sub(lambda match: f"{START_KW}{match.group(0)}{END_KW}", input)


KEYWORDS = [
    "Deathtouch",
    "Defender",
    "Double strike",
    "Enchant",
    "Equip",
    "First strike",
    "Flash",
    "Flying",
    "Haste",
    "Hexproof",
    "Indestructible",
    "Intimidate",
    "Landwalk",
    "Lifelink",
    "Protection",
    "Reach",
    "Shroud",
    "Trample",
    "Vigilance",
    "Ward",
    "Banding",
    "Rampage",
    "Cumulative upkeep",
    "Flanking",
    "Phasing",
    "Buyback",
    "Shadow",
    "Cycling",
    "Echo",
    "Horsemanship",
    "Fading",
    "Kicker",
    "Flashback",
    "Madness",
    "Fear",
    "Morph",
    "Amplify",
    "Provoke",
    "Storm",
    "Affinity",
    "Entwine",
    "Modular",
    "Sunburst",
    "Bushido",
    "Soulshift",
    "Splice",
    "Offering",
    "Ninjutsu",
    "Epic",
    "Convoke",
    "Dredge",
    "Transmute",
    "Bloodthirst",
    "Haunt",
    "Replicate",
    "Forecast",
    "Graft",
    "Recover",
    "Ripple",
    "Split second",
    "Suspend",
    "Vanishing",
    "Absorb",
    "Aura swap",
    "Delve",
    "Fortify",
    "Frenzy",
    "Gravestorm",
    "Poisonous",
    "Transfigure",
    "Champion",
    "Changeling",
    "Evoke",
    "Hideaway",
    "Prowl",
    "Reinforce",
    "Conspire",
    "Persist",
    "Wither",
    "Retrace",
    "Devour",
    "Exalted",
    "Unearth",
    "Cascade",
    "Annihilator",
    "Level up",
    "Rebound",
    "Umbra armor",
    "Infect",
    "Battle cry",
    "Living weapon",
    "Undying",
    "Miracle",
    "Soulbond",
    "Overload",
    "Scavenge",
    "Unleash",
    "Cipher",
    "Evolve",
    "Extort",
    "Fuse",
    "Bestow",
    "Tribute",
    "Dethrone",
    "Hidden agenda",
    "Outlast",
    "Prowess",
    "Dash",
    "Exploit",
    "Menace",
    "Renown",
    "Awaken",
    "Devoid",
    "Ingest",
    "Myriad",
    "Surge",
    "Skulk",
    "Emerge",
    "Escalate",
    "Melee",
    "Crew",
    "Fabricate",
    "Partner",
    "Undaunted",
    "Improvise",
    "Aftermath",
    "Embalm",
    "Eternalize",
    "Afflict",
    "Ascend",
    "Assist",
    "Jump-start",
    "Mentor",
    "Afterlife",
    "Riot",
    "Spectacle",
    "Escape",
    "Companion",
    "Mutate",
    "Encore",
    "Boast",
    "Foretell",
    "Demonstrate",
    "Daybound",
    "Nightbound",
    "Disturb",
    "Decayed",
    "Cleave",
    "Training",
    "Compleated",
    "Reconfigure",
    "Blitz",
    "Casualty",
    "Enlist",
    "Read ahead",
    "Ravenous",
    "Squad",
    "Space sculptor",
    "Visit",
    "Prototype",
    "Living metal",
    "More Than Meets the Eye",
    "For Mirrodin!",
    "Toxic",
    "Backup",
    "Bargain",
    "Craft",
    "Disguise",
    "Solved",
    "Plot",
    "Saddle",
    "Spree",
    "Freerunning",
    "Gift",
    "Offspring",
]

PATTERN = re.compile("|".join((k) for k in KEYWORDS), re.IGNORECASE)
