[project]
name = "moxcore"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = ["similarity", "moxc"]

[tool.uv.sources]
moxc = { workspace = true }

[tool.ruff]
line-length = 100
